### PR TITLE
No need to reshape here as all the data has been reshaped already.

### PR DESCRIPTION
**Pull request by wilderrodrigues**
The data is already reshaped in the beginning of the notebook, so no need to reshape it again when taking a random sample.

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Hi @jonkrohn,

I'm following your online course on GANs and DRL. Got an issue executing your notebook. For example, I get weird loss/accuracy and the GAN simply doesn't  work.

My code is a bit different, so I tried to run your and got the same results. I then tried running Grant's code, and still the same.

For instance, that's what I get after 500 epochs:
```
[D loss: 7.972398, acc: 0.500869]  [A loss: 0.032301, acc: 1.000000]
```

Any ideas?

Thanks in advance!

**Comment by jonkrohn** [comment]
Hi @wilderrodrigues, GANs are famously finicky, but I have run this GAN code dozens of times without issue, including today. I suspect there is some difference between your code and the LiveLessons notebook. If not that, then some difference in the input data.

**Comment by wilderrodrigues** [comment]
Thanks, @jonkrohn.

I also tried with Professor Rowel's code, but got similar results just like when running the code I wrote and your notebook. I'm running on a MacBook Pro, haven't tried on my GPU on AWS yet.

I will move on with the Reinforcement Learning part and look into this GAN issue later.

Thanks again!

Cheers, Wilder

**Comment by jonkrohn** [comment]
Ok cool. It shouldn't matter what hardware you run the model on, but hopefully you stumble across the issue! You could post a StackOverflow question as well detailing your issue.

**Pull request closed without merging**
